[package]
name = "bindings"
version = "2025.8.26"
edition = "2024"

[dependencies]
spacetimedb-sdk = { git = "https://github.com/vis-eyth/bitcraft-bindings", rev = "20731118b55bb5373e8d701cc62558510ae37d7b" }
tokio = { version = "1.47.1", features = ["sync"] }
